apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-producer-service
spec:
  type: NodePort
  selector:
    app: rabbitmq-producer-ex
  ports:
    - port: 9393
      targetPort: 9393
      nodePort: 31473  # NodePort range is typically between 30000-32767

